#lang racket/base

(require ffi/unsafe "define.rkt" "ctypes.rkt")

(define intrinsic-list (quote (
    adjust-trampoline
    alpha-umulh
    annotation
    arm-cdp
    arm-cdp2
    arm-get-fpscr
    arm-ldrexd
    arm-mcr
    arm-mcr2
    arm-mcrr
    arm-mcrr2
    arm-mrc
    arm-mrc2
    arm-neon-vabds
    arm-neon-vabdu
    arm-neon-vabs
    arm-neon-vacged
    arm-neon-vacgeq
    arm-neon-vacgtd
    arm-neon-vacgtq
    arm-neon-vaddhn
    arm-neon-vcls
    arm-neon-vclz
    arm-neon-vcnt
    arm-neon-vcvtfp2fxs
    arm-neon-vcvtfp2fxu
    arm-neon-vcvtfp2hf
    arm-neon-vcvtfxs2fp
    arm-neon-vcvtfxu2fp
    arm-neon-vcvthf2fp
    arm-neon-vhadds
    arm-neon-vhaddu
    arm-neon-vhsubs
    arm-neon-vhsubu
    arm-neon-vld1
    arm-neon-vld2
    arm-neon-vld2lane
    arm-neon-vld3
    arm-neon-vld3lane
    arm-neon-vld4
    arm-neon-vld4lane
    arm-neon-vmaxs
    arm-neon-vmaxu
    arm-neon-vmins
    arm-neon-vminu
    arm-neon-vmullp
    arm-neon-vmulls
    arm-neon-vmullu
    arm-neon-vmulp
    arm-neon-vpadals
    arm-neon-vpadalu
    arm-neon-vpadd
    arm-neon-vpaddls
    arm-neon-vpaddlu
    arm-neon-vpmaxs
    arm-neon-vpmaxu
    arm-neon-vpmins
    arm-neon-vpminu
    arm-neon-vqabs
    arm-neon-vqadds
    arm-neon-vqaddu
    arm-neon-vqdmlal
    arm-neon-vqdmlsl
    arm-neon-vqdmulh
    arm-neon-vqdmull
    arm-neon-vqmovns
    arm-neon-vqmovnsu
    arm-neon-vqmovnu
    arm-neon-vqneg
    arm-neon-vqrdmulh
    arm-neon-vqrshiftns
    arm-neon-vqrshiftnsu
    arm-neon-vqrshiftnu
    arm-neon-vqrshifts
    arm-neon-vqrshiftu
    arm-neon-vqshiftns
    arm-neon-vqshiftnsu
    arm-neon-vqshiftnu
    arm-neon-vqshifts
    arm-neon-vqshiftsu
    arm-neon-vqshiftu
    arm-neon-vqsubs
    arm-neon-vqsubu
    arm-neon-vraddhn
    arm-neon-vrecpe
    arm-neon-vrecps
    arm-neon-vrhadds
    arm-neon-vrhaddu
    arm-neon-vrshiftn
    arm-neon-vrshifts
    arm-neon-vrshiftu
    arm-neon-vrsqrte
    arm-neon-vrsqrts
    arm-neon-vrsubhn
    arm-neon-vshiftins
    arm-neon-vshiftls
    arm-neon-vshiftlu
    arm-neon-vshiftn
    arm-neon-vshifts
    arm-neon-vshiftu
    arm-neon-vst1
    arm-neon-vst2
    arm-neon-vst2lane
    arm-neon-vst3
    arm-neon-vst3lane
    arm-neon-vst4
    arm-neon-vst4lane
    arm-neon-vsubhn
    arm-neon-vtbl1
    arm-neon-vtbl2
    arm-neon-vtbl3
    arm-neon-vtbl4
    arm-neon-vtbx1
    arm-neon-vtbx2
    arm-neon-vtbx3
    arm-neon-vtbx4
    arm-qadd
    arm-qsub
    arm-set-fpscr
    arm-ssat
    arm-strexd
    arm-thread-pointer
    arm-usat
    arm-vcvtr
    arm-vcvtru
    atomic-cmp-swap
    atomic-load-add
    atomic-load-and
    atomic-load-max
    atomic-load-min
    atomic-load-nand
    atomic-load-or
    atomic-load-sub
    atomic-load-umax
    atomic-load-umin
    atomic-load-xor
    atomic-swap
    bswap
    convert-from-fp16
    convert-to-fp16
    convertff
    convertfsi
    convertfui
    convertsif
    convertss
    convertsu
    convertuif
    convertus
    convertuu
    cos
    ctlz
    ctpop
    cttz
    dbg-declare
    dbg-value
    eh-dwarf-cfa
    eh-exception
    eh-resume
    eh-return-i32
    eh-return-i64
    eh-selector
    eh-sjlj-callsite
    eh-sjlj-dispatch-setup
    eh-sjlj-longjmp
    eh-sjlj-lsda
    eh-sjlj-setjmp
    eh-typeid-for
    eh-unwind-init
    exp
    exp2
    expect
    flt-rounds
    fma
    frameaddress
    gcread
    gcroot
    gcwrite
    init-trampoline
    invariant-end
    invariant-start
    lifetime-end
    lifetime-start
    log
    log10
    log2
    longjmp
    memcpy
    memmove
    memory-barrier
    memset
    objectsize
    pcmarker
    pow
    powi
    ppc-altivec-dss
    ppc-altivec-dssall
    ppc-altivec-dst
    ppc-altivec-dstst
    ppc-altivec-dststt
    ppc-altivec-dstt
    ppc-altivec-lvebx
    ppc-altivec-lvehx
    ppc-altivec-lvewx
    ppc-altivec-lvsl
    ppc-altivec-lvsr
    ppc-altivec-lvx
    ppc-altivec-lvxl
    ppc-altivec-mfvscr
    ppc-altivec-mtvscr
    ppc-altivec-stvebx
    ppc-altivec-stvehx
    ppc-altivec-stvewx
    ppc-altivec-stvx
    ppc-altivec-stvxl
    ppc-altivec-vaddcuw
    ppc-altivec-vaddsbs
    ppc-altivec-vaddshs
    ppc-altivec-vaddsws
    ppc-altivec-vaddubs
    ppc-altivec-vadduhs
    ppc-altivec-vadduws
    ppc-altivec-vavgsb
    ppc-altivec-vavgsh
    ppc-altivec-vavgsw
    ppc-altivec-vavgub
    ppc-altivec-vavguh
    ppc-altivec-vavguw
    ppc-altivec-vcfsx
    ppc-altivec-vcfux
    ppc-altivec-vcmpbfp
    ppc-altivec-vcmpbfp-p
    ppc-altivec-vcmpeqfp
    ppc-altivec-vcmpeqfp-p
    ppc-altivec-vcmpequb
    ppc-altivec-vcmpequb-p
    ppc-altivec-vcmpequh
    ppc-altivec-vcmpequh-p
    ppc-altivec-vcmpequw
    ppc-altivec-vcmpequw-p
    ppc-altivec-vcmpgefp
    ppc-altivec-vcmpgefp-p
    ppc-altivec-vcmpgtfp
    ppc-altivec-vcmpgtfp-p
    ppc-altivec-vcmpgtsb
    ppc-altivec-vcmpgtsb-p
    ppc-altivec-vcmpgtsh
    ppc-altivec-vcmpgtsh-p
    ppc-altivec-vcmpgtsw
    ppc-altivec-vcmpgtsw-p
    ppc-altivec-vcmpgtub
    ppc-altivec-vcmpgtub-p
    ppc-altivec-vcmpgtuh
    ppc-altivec-vcmpgtuh-p
    ppc-altivec-vcmpgtuw
    ppc-altivec-vcmpgtuw-p
    ppc-altivec-vctsxs
    ppc-altivec-vctuxs
    ppc-altivec-vexptefp
    ppc-altivec-vlogefp
    ppc-altivec-vmaddfp
    ppc-altivec-vmaxfp
    ppc-altivec-vmaxsb
    ppc-altivec-vmaxsh
    ppc-altivec-vmaxsw
    ppc-altivec-vmaxub
    ppc-altivec-vmaxuh
    ppc-altivec-vmaxuw
    ppc-altivec-vmhaddshs
    ppc-altivec-vmhraddshs
    ppc-altivec-vminfp
    ppc-altivec-vminsb
    ppc-altivec-vminsh
    ppc-altivec-vminsw
    ppc-altivec-vminub
    ppc-altivec-vminuh
    ppc-altivec-vminuw
    ppc-altivec-vmladduhm
    ppc-altivec-vmsummbm
    ppc-altivec-vmsumshm
    ppc-altivec-vmsumshs
    ppc-altivec-vmsumubm
    ppc-altivec-vmsumuhm
    ppc-altivec-vmsumuhs
    ppc-altivec-vmulesb
    ppc-altivec-vmulesh
    ppc-altivec-vmuleub
    ppc-altivec-vmuleuh
    ppc-altivec-vmulosb
    ppc-altivec-vmulosh
    ppc-altivec-vmuloub
    ppc-altivec-vmulouh
    ppc-altivec-vnmsubfp
    ppc-altivec-vperm
    ppc-altivec-vpkpx
    ppc-altivec-vpkshss
    ppc-altivec-vpkshus
    ppc-altivec-vpkswss
    ppc-altivec-vpkswus
    ppc-altivec-vpkuhus
    ppc-altivec-vpkuwus
    ppc-altivec-vrefp
    ppc-altivec-vrfim
    ppc-altivec-vrfin
    ppc-altivec-vrfip
    ppc-altivec-vrfiz
    ppc-altivec-vrlb
    ppc-altivec-vrlh
    ppc-altivec-vrlw
    ppc-altivec-vrsqrtefp
    ppc-altivec-vsel
    ppc-altivec-vsl
    ppc-altivec-vslb
    ppc-altivec-vslh
    ppc-altivec-vslo
    ppc-altivec-vslw
    ppc-altivec-vsr
    ppc-altivec-vsrab
    ppc-altivec-vsrah
    ppc-altivec-vsraw
    ppc-altivec-vsrb
    ppc-altivec-vsrh
    ppc-altivec-vsro
    ppc-altivec-vsrw
    ppc-altivec-vsubcuw
    ppc-altivec-vsubsbs
    ppc-altivec-vsubshs
    ppc-altivec-vsubsws
    ppc-altivec-vsububs
    ppc-altivec-vsubuhs
    ppc-altivec-vsubuws
    ppc-altivec-vsum2sws
    ppc-altivec-vsum4sbs
    ppc-altivec-vsum4shs
    ppc-altivec-vsum4ubs
    ppc-altivec-vsumsws
    ppc-altivec-vupkhpx
    ppc-altivec-vupkhsb
    ppc-altivec-vupkhsh
    ppc-altivec-vupklpx
    ppc-altivec-vupklsb
    ppc-altivec-vupklsh
    ppc-dcba
    ppc-dcbf
    ppc-dcbi
    ppc-dcbst
    ppc-dcbt
    ppc-dcbtst
    ppc-dcbz
    ppc-dcbzl
    ppc-sync
    prefetch
    ptr-annotation
    ptx-bar-sync
    ptx-read-clock
    ptx-read-clock64
    ptx-read-ctaid-w
    ptx-read-ctaid-x
    ptx-read-ctaid-y
    ptx-read-ctaid-z
    ptx-read-gridid
    ptx-read-laneid
    ptx-read-lanemask-eq
    ptx-read-lanemask-ge
    ptx-read-lanemask-gt
    ptx-read-lanemask-le
    ptx-read-lanemask-lt
    ptx-read-nctaid-w
    ptx-read-nctaid-x
    ptx-read-nctaid-y
    ptx-read-nctaid-z
    ptx-read-nsmid
    ptx-read-ntid-w
    ptx-read-ntid-x
    ptx-read-ntid-y
    ptx-read-ntid-z
    ptx-read-nwarpid
    ptx-read-pm0
    ptx-read-pm1
    ptx-read-pm2
    ptx-read-pm3
    ptx-read-smid
    ptx-read-tid-w
    ptx-read-tid-x
    ptx-read-tid-y
    ptx-read-tid-z
    ptx-read-warpid
    readcyclecounter
    returnaddress
    sadd-with-overflow
    setjmp
    siglongjmp
    sigsetjmp
    sin
    smul-with-overflow
    spu-si-a
    spu-si-addx
    spu-si-ah
    spu-si-ahi
    spu-si-ai
    spu-si-and
    spu-si-andbi
    spu-si-andc
    spu-si-andhi
    spu-si-andi
    spu-si-bg
    spu-si-bgx
    spu-si-ceq
    spu-si-ceqb
    spu-si-ceqbi
    spu-si-ceqh
    spu-si-ceqhi
    spu-si-ceqi
    spu-si-cg
    spu-si-cgt
    spu-si-cgtb
    spu-si-cgtbi
    spu-si-cgth
    spu-si-cgthi
    spu-si-cgti
    spu-si-cgx
    spu-si-clgt
    spu-si-clgtb
    spu-si-clgtbi
    spu-si-clgth
    spu-si-clgthi
    spu-si-clgti
    spu-si-dfa
    spu-si-dfm
    spu-si-dfma
    spu-si-dfms
    spu-si-dfnma
    spu-si-dfnms
    spu-si-dfs
    spu-si-fa
    spu-si-fceq
    spu-si-fcgt
    spu-si-fcmeq
    spu-si-fcmgt
    spu-si-fm
    spu-si-fma
    spu-si-fms
    spu-si-fnms
    spu-si-fs
    spu-si-fsmbi
    spu-si-mpy
    spu-si-mpya
    spu-si-mpyh
    spu-si-mpyhh
    spu-si-mpyhha
    spu-si-mpyhhau
    spu-si-mpyhhu
    spu-si-mpyi
    spu-si-mpys
    spu-si-mpyu
    spu-si-mpyui
    spu-si-nand
    spu-si-nor
    spu-si-or
    spu-si-orbi
    spu-si-orc
    spu-si-orhi
    spu-si-ori
    spu-si-sf
    spu-si-sfh
    spu-si-sfhi
    spu-si-sfi
    spu-si-sfx
    spu-si-shli
    spu-si-shlqbi
    spu-si-shlqbii
    spu-si-shlqby
    spu-si-shlqbyi
    spu-si-xor
    spu-si-xorbi
    spu-si-xorhi
    spu-si-xori
    sqrt
    ssub-with-overflow
    stackprotector
    stackrestore
    stacksave
    trap
    uadd-with-overflow
    umul-with-overflow
    usub-with-overflow
    vacopy
    vaend
    var-annotation
    vastart
    x86-3dnow-pavgusb
    x86-3dnow-pf2id
    x86-3dnow-pfacc
    x86-3dnow-pfadd
    x86-3dnow-pfcmpeq
    x86-3dnow-pfcmpge
    x86-3dnow-pfcmpgt
    x86-3dnow-pfmax
    x86-3dnow-pfmin
    x86-3dnow-pfmul
    x86-3dnow-pfrcp
    x86-3dnow-pfrcpit1
    x86-3dnow-pfrcpit2
    x86-3dnow-pfrsqit1
    x86-3dnow-pfrsqrt
    x86-3dnow-pfsub
    x86-3dnow-pfsubr
    x86-3dnow-pi2fd
    x86-3dnow-pmulhrw
    x86-3dnowa-pf2iw
    x86-3dnowa-pfnacc
    x86-3dnowa-pfpnacc
    x86-3dnowa-pi2fw
    x86-3dnowa-pswapd
    x86-aesni-aesdec
    x86-aesni-aesdeclast
    x86-aesni-aesenc
    x86-aesni-aesenclast
    x86-aesni-aesimc
    x86-aesni-aeskeygenassist
    x86-avx-addsub-pd-256
    x86-avx-addsub-ps-256
    x86-avx-blend-pd-256
    x86-avx-blend-ps-256
    x86-avx-blendv-pd-256
    x86-avx-blendv-ps-256
    x86-avx-cmp-pd-256
    x86-avx-cmp-ps-256
    x86-avx-cvt-pd2-ps-256
    x86-avx-cvt-pd2dq-256
    x86-avx-cvt-ps2-pd-256
    x86-avx-cvt-ps2dq-256
    x86-avx-cvtdq2-pd-256
    x86-avx-cvtdq2-ps-256
    x86-avx-cvtt-pd2dq-256
    x86-avx-cvtt-ps2dq-256
    x86-avx-dp-ps-256
    x86-avx-hadd-pd-256
    x86-avx-hadd-ps-256
    x86-avx-hsub-pd-256
    x86-avx-hsub-ps-256
    x86-avx-ldu-dq-256
    x86-avx-loadu-dq-256
    x86-avx-loadu-pd-256
    x86-avx-loadu-ps-256
    x86-avx-maskload-pd
    x86-avx-maskload-pd-256
    x86-avx-maskload-ps
    x86-avx-maskload-ps-256
    x86-avx-maskstore-pd
    x86-avx-maskstore-pd-256
    x86-avx-maskstore-ps
    x86-avx-maskstore-ps-256
    x86-avx-max-pd-256
    x86-avx-max-ps-256
    x86-avx-min-pd-256
    x86-avx-min-ps-256
    x86-avx-movmsk-pd-256
    x86-avx-movmsk-ps-256
    x86-avx-movnt-dq-256
    x86-avx-movnt-pd-256
    x86-avx-movnt-ps-256
    x86-avx-ptestc-256
    x86-avx-ptestnzc-256
    x86-avx-ptestz-256
    x86-avx-rcp-ps-256
    x86-avx-round-pd-256
    x86-avx-round-ps-256
    x86-avx-rsqrt-ps-256
    x86-avx-sqrt-pd-256
    x86-avx-sqrt-ps-256
    x86-avx-storeu-dq-256
    x86-avx-storeu-pd-256
    x86-avx-storeu-ps-256
    x86-avx-vbroadcast-sd-256
    x86-avx-vbroadcastf128-pd-256
    x86-avx-vbroadcastf128-ps-256
    x86-avx-vbroadcastss
    x86-avx-vbroadcastss-256
    x86-avx-vextractf128-pd-256
    x86-avx-vextractf128-ps-256
    x86-avx-vextractf128-si-256
    x86-avx-vinsertf128-pd-256
    x86-avx-vinsertf128-ps-256
    x86-avx-vinsertf128-si-256
    x86-avx-vperm2f128-pd-256
    x86-avx-vperm2f128-ps-256
    x86-avx-vperm2f128-si-256
    x86-avx-vpermil-pd
    x86-avx-vpermil-pd-256
    x86-avx-vpermil-ps
    x86-avx-vpermil-ps-256
    x86-avx-vpermilvar-pd
    x86-avx-vpermilvar-pd-256
    x86-avx-vpermilvar-ps
    x86-avx-vpermilvar-ps-256
    x86-avx-vtestc-pd
    x86-avx-vtestc-pd-256
    x86-avx-vtestc-ps
    x86-avx-vtestc-ps-256
    x86-avx-vtestnzc-pd
    x86-avx-vtestnzc-pd-256
    x86-avx-vtestnzc-ps
    x86-avx-vtestnzc-ps-256
    x86-avx-vtestz-pd
    x86-avx-vtestz-pd-256
    x86-avx-vtestz-ps
    x86-avx-vtestz-ps-256
    x86-avx-vzeroall
    x86-avx-vzeroupper
    x86-int
    x86-mmx-emms
    x86-mmx-femms
    x86-mmx-maskmovq
    x86-mmx-movnt-dq
    x86-mmx-packssdw
    x86-mmx-packsswb
    x86-mmx-packuswb
    x86-mmx-padd-b
    x86-mmx-padd-d
    x86-mmx-padd-q
    x86-mmx-padd-w
    x86-mmx-padds-b
    x86-mmx-padds-w
    x86-mmx-paddus-b
    x86-mmx-paddus-w
    x86-mmx-palignr-b
    x86-mmx-pand
    x86-mmx-pandn
    x86-mmx-pavg-b
    x86-mmx-pavg-w
    x86-mmx-pcmpeq-b
    x86-mmx-pcmpeq-d
    x86-mmx-pcmpeq-w
    x86-mmx-pcmpgt-b
    x86-mmx-pcmpgt-d
    x86-mmx-pcmpgt-w
    x86-mmx-pextr-w
    x86-mmx-pinsr-w
    x86-mmx-pmadd-wd
    x86-mmx-pmaxs-w
    x86-mmx-pmaxu-b
    x86-mmx-pmins-w
    x86-mmx-pminu-b
    x86-mmx-pmovmskb
    x86-mmx-pmulh-w
    x86-mmx-pmulhu-w
    x86-mmx-pmull-w
    x86-mmx-pmulu-dq
    x86-mmx-por
    x86-mmx-psad-bw
    x86-mmx-psll-d
    x86-mmx-psll-q
    x86-mmx-psll-w
    x86-mmx-pslli-d
    x86-mmx-pslli-q
    x86-mmx-pslli-w
    x86-mmx-psra-d
    x86-mmx-psra-w
    x86-mmx-psrai-d
    x86-mmx-psrai-w
    x86-mmx-psrl-d
    x86-mmx-psrl-q
    x86-mmx-psrl-w
    x86-mmx-psrli-d
    x86-mmx-psrli-q
    x86-mmx-psrli-w
    x86-mmx-psub-b
    x86-mmx-psub-d
    x86-mmx-psub-q
    x86-mmx-psub-w
    x86-mmx-psubs-b
    x86-mmx-psubs-w
    x86-mmx-psubus-b
    x86-mmx-psubus-w
    x86-mmx-punpckhbw
    x86-mmx-punpckhdq
    x86-mmx-punpckhwd
    x86-mmx-punpcklbw
    x86-mmx-punpckldq
    x86-mmx-punpcklwd
    x86-mmx-pxor
    x86-sse2-add-sd
    x86-sse2-clflush
    x86-sse2-cmp-pd
    x86-sse2-cmp-sd
    x86-sse2-comieq-sd
    x86-sse2-comige-sd
    x86-sse2-comigt-sd
    x86-sse2-comile-sd
    x86-sse2-comilt-sd
    x86-sse2-comineq-sd
    x86-sse2-cvtdq2pd
    x86-sse2-cvtdq2ps
    x86-sse2-cvtpd2dq
    x86-sse2-cvtpd2ps
    x86-sse2-cvtps2dq
    x86-sse2-cvtps2pd
    x86-sse2-cvtsd2si
    x86-sse2-cvtsd2si64
    x86-sse2-cvtsd2ss
    x86-sse2-cvtsi2sd
    x86-sse2-cvtsi642sd
    x86-sse2-cvtss2sd
    x86-sse2-cvttpd2dq
    x86-sse2-cvttps2dq
    x86-sse2-cvttsd2si
    x86-sse2-cvttsd2si64
    x86-sse2-div-sd
    x86-sse2-lfence
    x86-sse2-maskmov-dqu
    x86-sse2-max-pd
    x86-sse2-max-sd
    x86-sse2-mfence
    x86-sse2-min-pd
    x86-sse2-min-sd
    x86-sse2-movmsk-pd
    x86-sse2-mul-sd
    x86-sse2-packssdw-128
    x86-sse2-packsswb-128
    x86-sse2-packuswb-128
    x86-sse2-padds-b
    x86-sse2-padds-w
    x86-sse2-paddus-b
    x86-sse2-paddus-w
    x86-sse2-pavg-b
    x86-sse2-pavg-w
    x86-sse2-pcmpeq-b
    x86-sse2-pcmpeq-d
    x86-sse2-pcmpeq-w
    x86-sse2-pcmpgt-b
    x86-sse2-pcmpgt-d
    x86-sse2-pcmpgt-w
    x86-sse2-pmadd-wd
    x86-sse2-pmaxs-w
    x86-sse2-pmaxu-b
    x86-sse2-pmins-w
    x86-sse2-pminu-b
    x86-sse2-pmovmskb-128
    x86-sse2-pmulh-w
    x86-sse2-pmulhu-w
    x86-sse2-pmulu-dq
    x86-sse2-psad-bw
    x86-sse2-psll-d
    x86-sse2-psll-dq
    x86-sse2-psll-dq-bs
    x86-sse2-psll-q
    x86-sse2-psll-w
    x86-sse2-pslli-d
    x86-sse2-pslli-q
    x86-sse2-pslli-w
    x86-sse2-psra-d
    x86-sse2-psra-w
    x86-sse2-psrai-d
    x86-sse2-psrai-w
    x86-sse2-psrl-d
    x86-sse2-psrl-dq
    x86-sse2-psrl-dq-bs
    x86-sse2-psrl-q
    x86-sse2-psrl-w
    x86-sse2-psrli-d
    x86-sse2-psrli-q
    x86-sse2-psrli-w
    x86-sse2-psubs-b
    x86-sse2-psubs-w
    x86-sse2-psubus-b
    x86-sse2-psubus-w
    x86-sse2-sqrt-pd
    x86-sse2-sqrt-sd
    x86-sse2-storel-dq
    x86-sse2-storeu-dq
    x86-sse2-storeu-pd
    x86-sse2-sub-sd
    x86-sse2-ucomieq-sd
    x86-sse2-ucomige-sd
    x86-sse2-ucomigt-sd
    x86-sse2-ucomile-sd
    x86-sse2-ucomilt-sd
    x86-sse2-ucomineq-sd
    x86-sse3-addsub-pd
    x86-sse3-addsub-ps
    x86-sse3-hadd-pd
    x86-sse3-hadd-ps
    x86-sse3-hsub-pd
    x86-sse3-hsub-ps
    x86-sse3-ldu-dq
    x86-sse3-monitor
    x86-sse3-mwait
    x86-sse41-blendpd
    x86-sse41-blendps
    x86-sse41-blendvpd
    x86-sse41-blendvps
    x86-sse41-dppd
    x86-sse41-dpps
    x86-sse41-extractps
    x86-sse41-insertps
    x86-sse41-movntdqa
    x86-sse41-mpsadbw
    x86-sse41-packusdw
    x86-sse41-pblendvb
    x86-sse41-pblendw
    x86-sse41-pcmpeqq
    x86-sse41-pextrb
    x86-sse41-pextrd
    x86-sse41-pextrq
    x86-sse41-phminposuw
    x86-sse41-pmaxsb
    x86-sse41-pmaxsd
    x86-sse41-pmaxud
    x86-sse41-pmaxuw
    x86-sse41-pminsb
    x86-sse41-pminsd
    x86-sse41-pminud
    x86-sse41-pminuw
    x86-sse41-pmovsxbd
    x86-sse41-pmovsxbq
    x86-sse41-pmovsxbw
    x86-sse41-pmovsxdq
    x86-sse41-pmovsxwd
    x86-sse41-pmovsxwq
    x86-sse41-pmovzxbd
    x86-sse41-pmovzxbq
    x86-sse41-pmovzxbw
    x86-sse41-pmovzxdq
    x86-sse41-pmovzxwd
    x86-sse41-pmovzxwq
    x86-sse41-pmuldq
    x86-sse41-ptestc
    x86-sse41-ptestnzc
    x86-sse41-ptestz
    x86-sse41-round-pd
    x86-sse41-round-ps
    x86-sse41-round-sd
    x86-sse41-round-ss
    x86-sse42-crc32-32-16
    x86-sse42-crc32-32-32
    x86-sse42-crc32-32-8
    x86-sse42-crc32-64-64
    x86-sse42-crc32-64-8
    x86-sse42-pcmpestri128
    x86-sse42-pcmpestria128
    x86-sse42-pcmpestric128
    x86-sse42-pcmpestrio128
    x86-sse42-pcmpestris128
    x86-sse42-pcmpestriz128
    x86-sse42-pcmpestrm128
    x86-sse42-pcmpgtq
    x86-sse42-pcmpistri128
    x86-sse42-pcmpistria128
    x86-sse42-pcmpistric128
    x86-sse42-pcmpistrio128
    x86-sse42-pcmpistris128
    x86-sse42-pcmpistriz128
    x86-sse42-pcmpistrm128
    x86-sse-add-ss
    x86-sse-cmp-ps
    x86-sse-cmp-ss
    x86-sse-comieq-ss
    x86-sse-comige-ss
    x86-sse-comigt-ss
    x86-sse-comile-ss
    x86-sse-comilt-ss
    x86-sse-comineq-ss
    x86-sse-cvtpd2pi
    x86-sse-cvtpi2pd
    x86-sse-cvtpi2ps
    x86-sse-cvtps2pi
    x86-sse-cvtsi2ss
    x86-sse-cvtsi642ss
    x86-sse-cvtss2si
    x86-sse-cvtss2si64
    x86-sse-cvttpd2pi
    x86-sse-cvttps2pi
    x86-sse-cvttss2si
    x86-sse-cvttss2si64
    x86-sse-div-ss
    x86-sse-ldmxcsr
    x86-sse-max-ps
    x86-sse-max-ss
    x86-sse-min-ps
    x86-sse-min-ss
    x86-sse-movmsk-ps
    x86-sse-mul-ss
    x86-sse-pshuf-w
    x86-sse-rcp-ps
    x86-sse-rcp-ss
    x86-sse-rsqrt-ps
    x86-sse-rsqrt-ss
    x86-sse-sfence
    x86-sse-sqrt-ps
    x86-sse-sqrt-ss
    x86-sse-stmxcsr
    x86-sse-storeu-ps
    x86-sse-sub-ss
    x86-sse-ucomieq-ss
    x86-sse-ucomige-ss
    x86-sse-ucomigt-ss
    x86-sse-ucomile-ss
    x86-sse-ucomilt-ss
    x86-sse-ucomineq-ss
    x86-ssse3-pabs-b
    x86-ssse3-pabs-b-128
    x86-ssse3-pabs-d
    x86-ssse3-pabs-d-128
    x86-ssse3-pabs-w
    x86-ssse3-pabs-w-128
    x86-ssse3-phadd-d
    x86-ssse3-phadd-d-128
    x86-ssse3-phadd-sw
    x86-ssse3-phadd-sw-128
    x86-ssse3-phadd-w
    x86-ssse3-phadd-w-128
    x86-ssse3-phsub-d
    x86-ssse3-phsub-d-128
    x86-ssse3-phsub-sw
    x86-ssse3-phsub-sw-128
    x86-ssse3-phsub-w
    x86-ssse3-phsub-w-128
    x86-ssse3-pmadd-ub-sw
    x86-ssse3-pmadd-ub-sw-128
    x86-ssse3-pmul-hr-sw
    x86-ssse3-pmul-hr-sw-128
    x86-ssse3-pshuf-b
    x86-ssse3-pshuf-b-128
    x86-ssse3-psign-b
    x86-ssse3-psign-b-128
    x86-ssse3-psign-d
    x86-ssse3-psign-d-128
    x86-ssse3-psign-w
    x86-ssse3-psign-w-128
    xcore-bitrev
    xcore-checkevent
    xcore-chkct
    xcore-clre
    xcore-clrsr
    xcore-crc32
    xcore-crc8
    xcore-eeu
    xcore-endin
    xcore-freer
    xcore-geted
    xcore-getet
    xcore-getid
    xcore-getps
    xcore-getr
    xcore-getst
    xcore-getts
    xcore-in
    xcore-inct
    xcore-initcp
    xcore-initdp
    xcore-initlr
    xcore-initpc
    xcore-initsp
    xcore-inshr
    xcore-int
    xcore-mjoin
    xcore-msync
    xcore-out
    xcore-outct
    xcore-outshr
    xcore-outt
    xcore-peek
    xcore-setc
    xcore-setclk
    xcore-setd
    xcore-setev
    xcore-setps
    xcore-setpsc
    xcore-setpt
    xcore-setrdy
    xcore-setsr
    xcore-settw
    xcore-setv
    xcore-sext
    xcore-ssync
    xcore-syncr
    xcore-testct
    xcore-testwct
    xcore-waitevent
    xcore-zext
    )))

(define LLVMIntrinsic (_enum 
 `(not-instrinsic = 0
   ,@intrinsic-list)))

(provide safe:LLVMGetIntrinsic)


(define-llvm-racket-unsafe LLVMGetIntrinsic
  (_fun (mod id types) ::
   (mod : LLVMModuleRef)
   (id : LLVMIntrinsic)
   (types : (_list i LLVMTypeRef))
   (_uint = (length types)) ->
   LLVMValueRef))

(define-llvm-racket-safe LLVMGetIntrinsic
  (_fun (mod id types) ::
   (mod : safe:LLVMModuleRef)
   (id : LLVMIntrinsic)
   (types : (_list i safe:LLVMTypeRef))
   (_uint = (length types)) ->
   (ptr : _pointer) ->
   (safe:llvm-value-ref ptr mod)))








